### ISSUE TITLE
Oracle DB Connection

### ISSUE THREAD

**Issue by ArunLamkhade** [msathis/SQLToNoSQLImporter#13]
Can you please share configuration file settings / steps for Oracle Database?

**Comment by ArunLamkhade** [comment]
I am trying to import values from Oracle DB to AWS Elasticsearch.

**Comment by msathis** [comment]
https://github.com/msathis/SQLToNoSQLImporter/blob/master/src/main/resources/db-data-config.xml

This file has sample configuration. Modify this for constructing the data as per your requirement.

**Comment by ArunLamkhade** [comment]
Thanks for quick update.

My import.properties file is
------------------------------------
#common properties
sql-data-config-file=db-data-config.xml
autoCommitSize=5000000
#available values are mongo,es,couch
dataStoreType=es

#Elastic-Search related properties
es.cluster.name=<esname>.us-east-1.es.amazonaws.com
#if you want to connect to multiple nodes for parallel indexing
# give them as comma separated.
es.hosts=<esname>.us-east-1.es.amazonaws.com
es.index.name=twitter1
es.index.type=user
------------------------------------

I am getting below error. Can you please help if something I am doing wrong?
===================
09:28:08,643  INFO plugins:118 - [Speed Demon] loaded [], sites []
09:28:39,960  INFO DataImporter:137 - Data Configuration loaded successfully
09:28:39,965 ERROR DataImporter:181 - *****  Data import failed. **********
 Reason is :
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.valueOf(Integer.java:766)
        at net.sathis.export.sql.DocBuilder.execute(DocBuilder.java:89)
        at net.sathis.export.sql.DataImporter.doFullImport(DataImporter.java:177)
        at net.sathis.export.sql.DataImporter.doDataImport(DataImporter.java:96)
        at net.sathis.export.sql.SQLToNoSQLImporter.main(SQLToNoSQLImporter.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:748)
===================

**Comment by ArunLamkhade** [comment]
Any update?

**Comment by msathis** [comment]
Can you please share the query? I think you have nullable int column.
