### ISSUE TITLE
com.mongodb.MongoTimeoutException: Timed out while waiting for a server that matches AnyServerSelector{} after 10000 ms

### ISSUE THREAD

**Issue by charyorde** [msathis/SQLToNoSQLImporter#2]
Hi,
After modifying the config files appropriately, I'm seeing the following errors when I execute `mvn test`.

```
com.mongodb.MongoTimeoutException: Timed out while waiting for a server that matches AnyServerSelector{} after 10000 ms
        at com.mongodb.BaseCluster.getServer(BaseCluster.java:87)
        at com.mongodb.DBTCPConnector.getServer(DBTCPConnector.java:654)
        at com.mongodb.DBTCPConnector.access$300(DBTCPConnector.java:39)
        at com.mongodb.DBTCPConnector$MyPort.getConnection(DBTCPConnector.java:503)
        at com.mongodb.DBTCPConnector$MyPort.get(DBTCPConnector.java:451)
        at com.mongodb.DBTCPConnector.getPrimaryPort(DBTCPConnector.java:409)
        at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:182)
        at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:165)
        at com.mongodb.DBCollection.insert(DBCollection.java:161)
        at com.mongodb.DBCollection.insert(DBCollection.java:147)
        at net.sathis.export.sql.mongo.MongoWriter.writeToNoSQL(MongoWriter.java:66)
        at net.sathis.export.sql.DocBuilder.execute(DocBuilder.java:130)
        at net.sathis.export.sql.DataImporter.doFullImport(DataImporter.java:177)
        at net.sathis.export.sql.DataImporter.doDataImport(DataImporter.java:96)
        at net.sathis.export.sql.SQLToNoSQLImporter.main(SQLToNoSQLImporter.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:744)
```

What could be causing this?

JDK 7, OSX, Mongo 2.6.32

**Comment by Yingmin-Li** [comment]
In my case, it does not work

**Comment by msathis** [comment]
@Yingmin-Li  Can you please post your stack trace?
